# fly.toml app configuration file generated for process-pending-jobs on 2024-12-26T13:07:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'process-pending-jobs'
primary_region = 'mia'

[build]
  dockerfile = 'pending_audio_jobs_script.Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
